# Generated by Django 5.0.6 on 2024-05-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='professional',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
