# Generated by Django 5.0.6 on 2024-06-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('link', models.URLField(max_length=500)),
                ('source', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('content', models.JSONField()),
            ],
            options={
                'indexes': [models.Index(fields=['title'], name='main_articl_title_21091c_idx'), models.Index(fields=['published'], name='main_articl_publish_5848ae_idx'), models.Index(fields=['source'], name='main_articl_source_f3afcf_idx')],
            },
        ),
    ]
