# Generated by Django 3.2.5 on 2024-06-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('link', models.URLField(max_length=500)),
                ('source', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('content', models.JSONField()),
            ],
        ),
    ]
