# Generated by Django 5.0.6 on 2024-06-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('published_date', models.DateField()),
            ],
            options={
                'indexes': [models.Index(fields=['title'], name='searchFunct_title_cf9490_idx'), models.Index(fields=['published_date'], name='searchFunct_publish_01e2e4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('location', models.CharField(default='', max_length=100)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='searchFunct_name_2268a3_idx'), models.Index(fields=['date'], name='searchFunct_date_ee040a_idx'), models.Index(fields=['location'], name='searchFunct_locatio_29812d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=10)),
                ('location', models.CharField(default='', max_length=100)),
            ],
            options={
                'indexes': [models.Index(fields=['last_name'], name='searchFunct_last_na_1dfab4_idx'), models.Index(fields=['profession'], name='searchFunct_profess_25acd3_idx'), models.Index(fields=['location'], name='searchFunct_locatio_24702e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='searchFunct_name_3cbe2d_idx'), models.Index(fields=['location'], name='searchFunct_locatio_ed55f5_idx')],
            },
        ),
    ]
